package com.myspace.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Leave Application")
public class LeaveApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Employee Id")
	private java.lang.Integer employeeId;
	@org.kie.api.definition.type.Label(value = "Leave Type")
	private java.lang.String leaveType;
	@org.kie.api.definition.type.Label(value = "Leave Balance")
	private java.lang.Integer leaveBalance;
	@org.kie.api.definition.type.Label(value = "Leaves Applied")
	private java.lang.Integer leavesApplied;
	@org.kie.api.definition.type.Label(value = "Years in company")
	private java.lang.Integer experience;
	@org.kie.api.definition.type.Label(value = "Leave Status")
	private java.lang.String leaveStatus;

	public LeaveApplication() {
	}

	public java.lang.Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(java.lang.Integer employeeId) {
		this.employeeId = employeeId;
	}

	public java.lang.String getLeaveType() {
		return this.leaveType;
	}

	public void setLeaveType(java.lang.String leaveType) {
		this.leaveType = leaveType;
	}

	public java.lang.Integer getLeaveBalance() {
		return this.leaveBalance;
	}

	public void setLeaveBalance(java.lang.Integer leaveBalance) {
		this.leaveBalance = leaveBalance;
	}

	public java.lang.Integer getLeavesApplied() {
		return this.leavesApplied;
	}

	public void setLeavesApplied(java.lang.Integer leavesApplied) {
		this.leavesApplied = leavesApplied;
	}

	public java.lang.Integer getExperience() {
		return this.experience;
	}

	public void setExperience(java.lang.Integer experience) {
		this.experience = experience;
	}

	public java.lang.String getLeaveStatus() {
		return this.leaveStatus;
	}

	public void setLeaveStatus(java.lang.String leaveStatus) {
		this.leaveStatus = leaveStatus;
	}

	public LeaveApplication(java.lang.Integer employeeId,
			java.lang.String leaveType, java.lang.Integer leaveBalance,
			java.lang.Integer leavesApplied, java.lang.Integer experience,
			java.lang.String leaveStatus) {
		this.employeeId = employeeId;
		this.leaveType = leaveType;
		this.leaveBalance = leaveBalance;
		this.leavesApplied = leavesApplied;
		this.experience = experience;
		this.leaveStatus = leaveStatus;
	}

}